- name: 'ContactsManager'
  uriPattern: 'contacts/{@action}'
  defaults:
    '@package': 'WellGroup.ContactsManager'
    '@controller': 'Contact'
    '@action': 'list'
  routeParts:
    contact:
      objectType: 'WellGroup\ContactsManager\Domain\Model\Contact'
