- name: 'Contacts Manager'
  uriPattern: 'contacts(/{@action})'
  defaults:
    '@package': 'WellGroup.ContactsManager'
    '@controller': 'Contact'
    '@action': 'index'
    '@format': 'html'
  routeParts:
    contact:
      objectType: 'WellGroup\ContactsManager\Domain\Model\Contact'
  appendExceedingArguments: true

